### ISSUE TITLE
仕様を考える　(仮)

### ISSUE THREAD

**Issue by KentyK** [AtsushiHosaka/Clear-Vision#14]

**Comment by AtsushiHosaka** [comment]
・ARでリアルタイムで画像を加工して見やすくする

・写真フォルダにある画像も加工して見やすくできるようにする、その加工された画像も保存できるようにしたらいいかも

・加工の方法は、本来の色が見えやすくすることではなく、その人にとって見やすい色として画像を再構築する方がいいと思う。白黒映画みたいな。それなら見分けづらい色の識別が簡易になる

・写真の一部をタップした時、そこの色が何色なのかを表示するようにする

・色盲の型の診断機能、１〜３型、二色盲や三色覚異常など種類があるのでそれを特定する

・個人個人の色盲の度合いを数値化する、RGB錐体の量を比とか通常と比べての割合とかで表せると画像加工の時に使いやすいはず。

・いつでも色盲の度合いは再診断と再設定できるようにする

・いろんな国の人にも使ってもらいたいので、言語も色々と追加する
